### ISSUE TITLE
Final Push Meta Bug

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#104]
## Proposed timeline:
* 2/26 - 3/2: Close P1s, seek UX sign-off
* 3/5: Send intent-to-ship e-mail to RelMan
* 3/5 - 3/9: Final QA/Engineering review
  - If this takes longer, we will push back the launch date to 3/19
* 3/12: Launch study

### Open P1 issues
- [ ] #133 
- [ ] #132 
- [ ] #131 
- [ ] #130 
- [ ] #125 
- [ ] #122  
- [ ] #27 
- [ ] #62 (PR #102 did the first half; still needs TELEMETRY.md; Kamyar to write)
- [ ] #28
- [ ] #26 

### Open P2 issues I'd still like to fix
- [ ] #97 
- [ ] #78 
- [ ] #75

**Comment by pdehaan** [comment]
> Would you object to any of the issues in the second list being addressed while you are actively doing final QA (estimated the week of 3/5 - 3/9)?

Sounds fair to me. :+1:

Is the list above final? I was casually trolling https://github.com/biancadanforth/tracking-protection-shield-study/issues?q=is%3Aopen+is%3Aissue+label%3AP1 and noticed we have 2 new-ish **P1** bugs, #124 and #125, that I can't see in the lists above.

**Comment by pdehaan** [comment]
We also have a P2, #72 _"Clean up bootstrap.js"_, which I don't see above.

**Comment by biancadanforth** [comment]
Hmm... On second thought, I'm thinking this meta bug is more trouble to maintain than it's worth. I think the goal here is to close all P1s. Time permitting, close P2s. If there are any P2s you think should be escalated, please comment in that issue. I certainly have my work cut out for me. :X Going to close this issue for now since it's more confusing than helpful.
