### ISSUE TITLE
Make sure units for ads/trackers are pluralized correctly

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#125]
I took care of this for time units in #65 , but not for ad(s) and tracker(s).

**Comment by pdehaan** [comment]
![fast-second-singular](https://user-images.githubusercontent.com/557895/37007539-949792a4-2092-11e8-9b83-111474989e13.png)

**Figure 1:** "fast" branch, with correct singular "1 second saved" string.

**Comment by pdehaan** [comment]
![national_and_local_weather_radar__daily_forecast__hurricane_and_information_from_the_weather_channel_and_weather_com](https://user-images.githubusercontent.com/557895/37053249-79b65fc6-2130-11e8-9c56-0081da2603db.png)
**Figure 3:** "private" branch, with **incorrect** plural of "1 ads blocked".

**Comment by pdehaan** [comment]
![new-tab-fast](https://user-images.githubusercontent.com/557895/37057992-fa67e39e-213d-11e8-9588-17d1b4bf394b.png)

I wasn't fast enough on my screenshots, but it did correctly pluralize "1 minute and 1 second" on the newtab page.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.2), retested on Windows 10 x64, Mac OS 10.12 and Ubuntu 16.04 with Unbranded Beta 59.0b14.
