### ISSUE TITLE
Couple of "TBD" comments in package.json

### ISSUE THREAD

**Issue by pdehaan** [biancadanforth/tracking-protection-shield-study#127]
Not sure if any of these block anything, but probably worth a quick look before release to see if they are valid, or from the template:

```sh
$ cat package.json | grep -i "tbd"
    "bugzilla": "<tbd: bug to attach for signing>",
    "sign": "echo 'TBD, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1407757'",
```

### `{addon.bugzilla: 'TBD:...'}`:
https://github.com/biancadanforth/tracking-protection-shield-study/blob/de4df346b233adbb74a2a51234ffc00ab867f816/package.json#L17

### `{scripts.sign: 'TBD:...'}`:
https://github.com/biancadanforth/tracking-protection-shield-study/blob/de4df346b233adbb74a2a51234ffc00ab867f816/package.json#L75

**Comment by biancadanforth** [comment]
Thanks for pointing these out! These are inherited from the template. Might be worth updating the Bugzilla one, though it's not used anywhere.
We don't have a sign script; I think that was aspirational. I can remove it for now.
