### ISSUE TITLE
XML Parsing Error in private browsing tab

### ISSUE THREAD

**Issue by pdehaan** [biancadanforth/tracking-protection-shield-study#137]
I'm in the "private" branch (via <kbd>$ npm run firefox</kbd>) and when I tried going to "File > New Private Window", I get the following:

```
XML Parsing Error: Location: jar:file:///Users/pdehaan/dev/github/mozilla/tracking-protection-shield-study/dist/linked-addon.xpi!/content/aboutPrivateBrowsingMod.xhtml Line Number 34, Column 76:
            accesskey="&privatebrowsingpage.openPrivateWindow.accesskey;"/>
---------------------------------------------------------------------------^
```

https://github.com/biancadanforth/tracking-protection-shield-study/blob/fb592fb55756642a6e1c746f52afd2a30ddb6619/addon/content/aboutPrivateBrowsingMod.xhtml#L30-L34

![pbmode](https://user-images.githubusercontent.com/557895/37054950-484cf526-2135-11e8-8e96-270295f1d83d.png)

**Comment by pdehaan** [comment]
Trying to run the xhtml through a linter (https://validator.w3.org/nu/#textarea) and I'm getting a oodles of errors.
I think the above error is this:

> [Error:] Self-closing syntax (`/>`) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
>
> From line 13, column 5; to line 17, column 76
>
> ```
> ;</p>↩
>    <button xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"↩
>            id="startPrivateBrowsing"↩
>            class="showNormal"↩
>            label="&privatebrowsingpage.openPrivateWindow.label;"↩
>            accesskey="&privatebrowsingpage.openPrivateWindow.accesskey;"/>↩
>    <d
> ```

I think it's saying that `<button>` isn't a self-closing tab, and it should be `<button ...></button>`.

**Comment by biancadanforth** [comment]
I literally just copied the XHTML file for `about:privatebrowsing` from the my local build of Firefox, so if there are parsing errors, I am surprised!

@pdehaan , What version of Firefox are you testing on? (ex: Nightly 60, Beta 59...)? I cannot reproduce this error unfortunately. Here's what I tried:
1. Force "private" treatment
2. `npm run firefox` in unbranded Beta (Firefox 59)
3. In the new window, click File > New Private Window

**Comment by pdehaan** [comment]
Nightly 60.0a1 (2018-03-05) (64-bit) on macOS via <kbd>npm run firefox</kbd>.
I'm still seeing the bahavior in **master**.

**Comment by biancadanforth** [comment]
That's really odd, because I am seeing that it works in both Nightly and Beta on Mac OS 64 bit:

### Nightly
![137-nightly](https://user-images.githubusercontent.com/17437436/37073811-f5ff7098-217d-11e8-826e-76442de84080.gif)

### Beta
![137-beta](https://user-images.githubusercontent.com/17437436/37073819-fc75c472-217d-11e8-9dbb-63a8d6deaacd.gif)

Why are we seeing different things? That's a little troubling. @rhelmer , any ideas?

**Comment by pdehaan** [comment]
I'm unable to repro on unbranded Firefox Beta 58.0.2 (64-bit macOS).

**Comment by pdehaan** [comment]
Also unable to repro on unbranded Firefox Beta 59.0b14 (64-bit macOS).

Dangerously close to just suggesting we close this if nobody else can repro. Or see if Softvision team can repro in a handful of environments.

**Comment by biancadanforth** [comment]
Going to close for now; I updated the TESTPLAN in PR #146 to check for this.
