### ISSUE TITLE
Odd text wrapping on about:home page

### ISSUE THREAD

**Issue by pdehaan** [biancadanforth/tracking-protection-shield-study#138]
Minor UI nit, but on the "private" branch I'm noticing the text wraps under the shield icon when you have an absurdly narrow window.

![abouthome](https://user-images.githubusercontent.com/557895/37057315-d0aee450-213b-11e8-9aba-fe11ee152903.png)

**Comment by biancadanforth** [comment]
Good observation! I would say this is a good observation, and relatively easy to fix, but non-blocking. Time-permitting I will fix it.

**Comment by pdehaan** [comment]
Yeah, probably P3. I was going to ping jsavory for her $0.03, but wasn't sure if she was on GitHub.

**Comment by biancadanforth** [comment]
@pdehaan What OS are you on? This is what it looks like for me:
<img width="738" alt="screen shot 2018-03-06 at 5 14 03 pm" src="https://user-images.githubusercontent.com/17437436/37068082-cf12ce74-2161-11e8-90bf-05bf10ac4f52.png">

**Comment by biancadanforth** [comment]
@jsavory, What do you think about the prioritization here?
