### ISSUE TITLE
The pageAction Badge is not displayed on Windows and Linux

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [biancadanforth/tracking-protection-shield-study#151]
[Affected versions]:
- Unbranded Beta 59.0b14

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have the latest Tracking Protection Messaging .xpi installed (v.1.0.1)

[Steps to reproduce]:
1. Open the browser and navigate to a website (e.g. www.cnn.com).
2. Observe the pageAction badge for Tracking Protection Messaging.

[Expected result]:
- The badge with a green background, Tracking Protection icon and specific value are displayed.

[Actual result]:
- The badge can't be seen, even though it's there.

[Notes]:
- Attached a screen recording of the issue.

![badge is missing](https://user-images.githubusercontent.com/26000308/37158054-151d85a2-22f3-11e8-8fcd-8785ce9b2de5.gif)

**Comment by biancadanforth** [comment]
Thanks Carmen. Definitely a P1, and I will look into this one right away.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible, tested on Windows 10 x64 and Ubuntu 16.04 x64 with Unbranded Beta 59.0b14 and the latest Tracking Protection Messaging .xpi installed (v.1.0.2).
