### ISSUE TITLE
Tracking Protection Messaging panel goes blank when showing the browser window in full screen

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [biancadanforth/tracking-protection-shield-study#152]
[Affected versions]:
- Unbranded Beta 59.0b14

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Tracking Protection Messaging .xpi installed (v.1.0.1)
- The browser was previously resized.

[Steps to reproduce]:
1. Open the browser and navigate to a website (e.g. www.cnn.com).
2. Click the pageAction badge for Tracking Protection Messaging in order to trigger the TPM door hanger.
3. Press "F11" key and observe the panel.

[Expected result]:
- The panel renders correctly with fullscreen.

[Actual result]:
- The panel goes blank.

[Notes]:
- This is also reproducible with the Intro panel.
- Attached a screen recording of the issue:

![full screen tpm](https://user-images.githubusercontent.com/26000308/37158677-9e72a46c-22f4-11e8-838a-397b271d7196.gif)

**Comment by biancadanforth** [comment]
Thanks Carmen for noting this! I'm thinking this may not be a P1, though I'm not sure how often users go into full screen mode (and do so particularly when the pageAction panel in this study is opened)... @gregglind, what do you think about priority?

**Comment by biancadanforth** [comment]
I may be able to code something quickly that just dismisses the panel if the user clicks out of the window (thinking the `deactivate` event). Not sure if that'd do it. Worth a shot probably.

**Comment by gregglind** [comment]
Details wanted... which sort of full screen, and what platform?  Windows or
OS X?

I would call this a P2, but it’s annoying.

**Comment by biancadanforth** [comment]
Says Windows platform and the kind of full screen you get when you press "F11".

**Comment by SoftVision-EmilPasca** [comment]
This issue is still reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.2), retested on Windows 10 x64 with Unbranded Beta 59.0b14.

**Comment by biancadanforth** [comment]
Ah yes, I fixed it for the intro panel but not the pageAction panel. Thank you. Re-opening.

**Comment by biancadanforth** [comment]
I just chatted with pdol (the stakeholder on this project), and he gave me the go-ahead to simply dismiss the panels (both intro and pageAction) on window resize. This will make this problem go away. Patch forthcoming.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.5), retested on Windows 10 x64 with Unbranded Beta 59.0b14.
