### ISSUE TITLE
Show timeSaved per page on pageAction?

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#16]
Per data collected in PR #14, most of the pages in my particular setup load in 1-5s.

This means for the "fast" messaging treatment branch, `timeSaved` per page from Tracking Protection (estimated to be 44% of page load time), is often between 0-3s.

![screen shot 2018-01-11 at 11 16 11 am](https://user-images.githubusercontent.com/17437436/34842789-629a49b8-f6c1-11e7-968a-1d2d28273201.png)

Is this a significant enough number to display on the pageAction badge?

Alternatives include:
* Using blocked resources per page instead, same as used for the "private" messaging treatment branch.
* Using total time saved during session (this is what is shown on the new tab page).
  * This would mean the pageAction would be showing a value that isn't per-page.
* Only showing the badge if the time saved exceeds a certain substantial value.
  * Realistically, this would mean a significant decrease in the number of times the pageAction is displayed, as virtually 100% of sites I have seen with my connection show 2s or less. Granted others may have slower connections/different set-ups and loading times can vary for the same site.

**Comment by biancadanforth** [comment]
@jsavory, what do you think?

**Comment by jsavory** [comment]
Works for me!

**Comment by biancadanforth** [comment]
Per my discussion with @jsavory, we're going to use a new estimate for time saved based on # of blocked resources with a reasonable cap. Page load time may still play a role in the calculation as well.
