### ISSUE TITLE
Tracking Protection Messaging Intro panel goes blank when maximizing the browser window 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [biancadanforth/tracking-protection-shield-study#161]
[Affected versions]:
- Unbranded Beta 59.0b14

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Tracking Protection Messaging .xpi installed (v.1.0.1)
- The browser was previously resized.

[Steps to reproduce]:
1. Open the browser and navigate to a website (e.g. www.cnn.com).
2. Wait for the Intro panel to be displayed.
3. Click the "Maximize" button from the left side of the "Close" browser button and observe what happens next.

[Expected result]:
- The panel renders correctly.

[Actual result]:
- The panel goes blank.

[Notes]:
- Attached a screen recording of the issue:

![maximize panel](https://user-images.githubusercontent.com/26000308/37216839-82b2e662-23c4-11e8-850d-4ef21b1ed298.gif)

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.2), retested on Windows 10 x64, Mac OS 10.12 and Ubuntu 16.04 with Unbranded Beta 59.0b14.

**Comment by biancadanforth** [comment]
Going to re-open, but my latest PR will close this per this [comment](https://github.com/biancadanforth/tracking-protection-shield-study/issues/152#issuecomment-372422816).

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.5), retested on Windows 10 x64 with Unbranded Beta 59.0b14.
