### ISSUE TITLE
End the study if the user has another ad-blocking add-on installed?

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#162]
From an e-mail with one of our QA team members, @SoftVision-CarmenFat:
> How should we handle the scenario in which an user installs during the study another adblocker addon? Shouldn't the study end in this case?
We've tested this with other tracker blockers addons installed like "uBlok" and "Ghostery" in which case the "Tracking Protection Shield Study" will no longer detect any trackers within the visited page.

This is a very good question, and I think you are right that we should probably check for those add-ons as an eligibility criterion for enrollment in the study as well as listen for if they are installed during the study. The three add-ons I can think of are uBlock, Ghostery and Disconnect.

@gregglind, just want to confirm with you that this is a good idea before embarking on this quest. :) I.e. that this is a P1? I know it's probably not a common scenario, but still seems like it would invalidate the study data for that user.

**Comment by biancadanforth** [comment]
I spoke with @MattGrimes, and he says we can check for this in Normandy as long as I provide the add-on ids and post it into the tracking bug in Bugzilla so that we remember to add these to the filter expressions. Normandy can check as an eligibility criteria for these add-ons and if the user installs one during the study, it will unenroll them within 24 hours.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.2), retested on Windows 10 x64, Mac OS 10.12 and Ubuntu 16.04 with Unbranded Beta 59.0b14.
