### ISSUE TITLE
[Windows] The vertical scrollbar is wrongly displayed in the "Intro panel" 

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [biancadanforth/tracking-protection-shield-study#173]
[Notes]:
- This issue is not reproducible on Mac or Linux.

[Affected versions]:
- Firefox Beta (59.0b14)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Tracking Protection Messaging .xpi installed (v.1.0.2)

[Steps to reproduce]:
- Open the browser with the profile from prerequisites.
- Navigate on a webpage with blocked resources (eg. www.cnn.com). 
- Observe the Intro panel.

[Expected result]:
- The Intro panel doesn't display any scrollbar.

[Actual result]:
- The Intro panel displays a vertical scrollbar.

[Additional Notes]:
- The issue is reproducible only on "private" branch.
- Attached a screen recording of the issue:
![scrollbar_issue](https://user-images.githubusercontent.com/20083658/37286581-02103b2e-260b-11e8-899e-70cbe54660e4.gif)

**Comment by biancadanforth** [comment]
Thanks Emil for finding this. This is the result of a workaround I did on Windows for #161 . I did a think you should never do: explicitly specify the height of the panel. I have an idea for how I can avoid doing that.

**Comment by biancadanforth** [comment]
There will be new behavior per this [comment](https://github.com/biancadanforth/tracking-protection-shield-study/issues/152#issuecomment-372422816). That will fix this issue; patch forthcoming.
