### ISSUE TITLE
The "Page Action" area is gradually moved to the left each time when a tab is opened in foreground

### ISSUE THREAD

**Issue by Softvision-MariusComan** [biancadanforth/tracking-protection-shield-study#178]
**[Affected Versions]:**
- Unbranded Firefox Beta (59.0b14) Build ID:20180301022608

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile.
- Have the following prefs. in the "about:config" page (If a preference does not exist, please create it):
	- “extensions.legacy.enabled” pref set to “true”;
	- “xpinstall.signatures.required” pref set to “false”;
	- “extensions.tracking_protection_messaging_study.variation_override” pref set to "fast".
- Have the latest "Tracking Protection Messaging Shield Study" add-on (1.0.3) installed.
- Have the "When you open a link in a new tab, switch to it immediately" option checked in the "about:preferences" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to any website (eg. https://www.reddit.com/).
2. Open a link in a new tab and switch back to the first.
3. Repeat step 2 at least 6 times and observe the address bar each time.

**[Expected result]:**
- All elements are in their places.

**[Actual result]:**
- The "Page action", "Save to Pocket" and "Bookmark" buttons are gradually moved to the left part of the address bar. 

**[Notes]:**
- The issue is reproducible only with pages where the "pageAction Badge" is displayed.
- The issue is also reproducible with the “extensions.tracking_protection_messaging_study.variation_override” pref set to "private".
- The "Page action", "Save to Pocket" and "Bookmark" buttons are correctly placed in a new window.
- The "Page action", "Save to Pocket" and "Bookmark" buttons are reset in all affected windows after a browser restart.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/37357373-f64a6210-26f0-11e8-982a-962949f9f08f.gif)

<img width="1280" alt="issue" src="https://user-images.githubusercontent.com/31243259/37357398-051b6316-26f1-11e8-9ea1-11d54c20b842.png">

**Comment by biancadanforth** [comment]
Wow that's really weird. I never noticed. Will check it out; thanks.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.5), retested on Windows 10 x64, Mac OS 10.13 and Ubuntu 16.04 with Unbranded Beta 59.0b14.
