### ISSUE TITLE
"Icon - Tracking Protection" tooltip is wrongly displayed when hovering the shield icon from the new tab

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [biancadanforth/tracking-protection-shield-study#186]
[Affected versions]:
- Unbranded Beta 59.0b14

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have the latest Tracking Protection Messaging .xpi installed (v.1.0.5)

[Steps to reproduce]:
1. Open the browser and navigate to a website (e.g. www.cnn.com).
2. Press "Ctrl"+"t" keys in order to open a new tab.
3. Hover the shield icon from the left side of the tracker text and observe the behavior.

[Expected result]:
- The text from the tooltip doesn't mention the "Icon -" part
OR
- There is no tooltip displayed.

[Actual result]:
- "Icon - Tracking Protection" tooltip is displayed.

[Notes]:
- This is reproducible on both "fast" and "private" variations. 
- Attached a screenshot  of the issue: 

![tooltip](https://user-images.githubusercontent.com/26000308/37411443-7b3be3b2-27ab-11e8-8217-3e7a61fe4ddd.png)

**Comment by biancadanforth** [comment]
Thanks Carmen; yes I had removed that previously until my middle-of-the-night-patch last night. I know exactly where I can remove this line; I'll fix it today. Calling this a P3, but it will be addressed.
