### ISSUE TITLE
Add end of study surveys

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#23]
Since we have 2 controls and 2 experimental branches, this study will have 4 different URLs for when a user from each of these 4 branches completes the study at the end of two weeks.

There may also be a fifth URL for those users who end the study early (i.e. by toggling tracking protection).

Per rrayborn (GitHub rayborn):
> It will just be `<url>?branch=<branchid>&state=<stateid)` if that works for you.  State being 'complete' or 'early-termination' (or something like that).  I don't think we'll need other URL params.

**Comment by biancadanforth** [comment]
@rayborn, If there is a survey for users who end the study by toggling tracking protection on/off (the fifth URL mentioned above), we should be sure not to add anything at the end of this survey about resetting TP. See Issue #21 for more details.

**Comment by biancadanforth** [comment]
URL format: `<url>?branch=<branchID>&reason=<reason>`

**1. Disable survey state codes**
* reason = `"user-disable"`: User has uninstalled the addon from `about:addons`
* reason= `"user-disabled-builtin-tracking-protection"`: User has lowered the level of Tracking Protection compared to their treatment branch from `about:preferences` or `about:config`.
* reason = `"user-enabled-builtin-tracking-protection"`: User has raised the level of Tracking Protection compared to their treatment branch from `about:preferences` or `about:config`.
* reason = `"introduction-confirmation-leave-study"`: User has opted to disable Tracking Protection from the Introduction panel confirmation screen.
* reason = `"page-action-confirmation-leave-study"`: User has opted to disable Tracking Protectionfrom the page action panel confirmation screen.

**2. End of Study reason codes**
* reason = `"expired"`: study has expired

**Study endings that won't bring the user to a survey:**
* reason = `"ineligible"`: User is ineligible for the study as determined by the `Config.study.isEligible()`.

**Comment by biancadanforth** [comment]
We currently have two survey links: one to a "Disable" survey and one to an "End of Study" survey.

The only difference between the Disable and End of Study surveys is a write in question. That write-in question is: "Why did you disable Tracking Protection in Firefox?"

There are study endings listed above in which the user can end the study before it expires without having disabled Tracking Protection:
* reason = `"user-enabled-builtin-tracking-protection"`: User has raised the level of Tracking Protection compared to their treatment branch from `about:preferences` or `about:config`.
* reason = `"user-disable"`: User has uninstalled the addon from `about:addons`

@rrayborn, what are our options here for adjusting the survey?

**Comment by rayborn** [comment]
I don't see many points where the survey itself would need altered.  I've modified the logic as follows:

- Treat these users as generic disables.  I don't think we need different flows.  Crosstabs will be of interest
  - reason=user-disable
  - reason=user-disabled-builtin-tracking-protection
  - reason=page-action-confirmation-leave-study
- Treat these users as generic completes.  I don't think we need different flows.  Crosstabs will be of interest.
  - reason=user-enabled-builtin-tracking-protection
  - reason=expired
- I'll follow up with the stakeholders about what we want to ask users who immediately opt-out.  I'm not certain we'll even want to survey these users, but it might be interesting to get an idea of their motivations
  - reason=introduction-confirmation-leave-study

**Comment by biancadanforth** [comment]
Okay thanks @rayborn . I have a few follow ups for you.
* What do you mean by "Crosstabs"?
* If I am hearing you right, there will only be two surveys: 1) generic disables and 2) generic completes.
* We need a decision on whether `introduction-confirmation-leave-study` falls into the generic disable or no survey bucket. When should I expect an answer on this?
* Will the survey links be the same URL as you sent before? If not, when should I expect those links?

Updated my endings/buckets below:

### Generic disables
**Standard endings**
* reason = `"user-disable"`: User has uninstalled the addon from `about:addons`

**Study-specific endings**
* reason= `"user-disabled-builtin-tracking-protection"`: User has lowered the level of Tracking Protection compared to their treatment branch from `about:preferences` or `about:config`.
* reason = `"page-action-confirmation-leave-study"`: User has opted to disable Tracking Protection from the page action panel confirmation screen.

### Generic completes
**Standard endings**
* reason = `"expired"`: study has expired

**Study-specific endings**
* reason = `"user-enabled-builtin-tracking-protection"`: User has raised the level of Tracking Protection compared to their treatment branch from `about:preferences` or `about:config`.

### No survey
**Standard endings**
* reason = `"ineligible"`: User is ineligible for the study as determined by the `Config.study.isEligible()`.


### TBD
**Study-specific endings**
* reason = `"introduction-confirmation-leave-study"`: User has opted to disable Tracking Protection from the Introduction panel confirmation screen.

**Comment by biancadanforth** [comment]
From rayborn:

> Alright, added tracking protection info to the end of the "expired" survey (and added a bit more of an explanation to the end of the other reasons too).
https://qsurvey.mozilla.com/collab/tp-perception?reason=user-disable
https://qsurvey.mozilla.com/collab/tp-perception?reason=user-disabled-builtin-tracking-protection
https://qsurvey.mozilla.com/collab/tp-perception?reason=page-action-confirmation-leave-study
https://qsurvey.mozilla.com/collab/tp-perception?reason=user-enabled-builtin-tracking-protection
https://qsurvey.mozilla.com/collab/tp-perception?reason=expired

**Comment by biancadanforth** [comment]
@rayborn : Thanks for sending me updated survey links! I have added them to the study. I took a look at each survey to make sure the questions made sense based on the exit condition. I found a couple discrepancies/issues. Can you fix these?
* The `user-disable` survey asks users why they disabled Tracking Protection. Since users arrive at this survey by manually uninstalling the addon in `about:addons`, I think this question should be removed.
* While the `page-action-confirmation-leave-study` survey asks the users why they disabled Tracking Protection, the `introduction-confirmation-leave-study` survey does not. It should!
* There's a misalignment between a click/focus effect and the stars on the star rating question. See screenshot below:
![screen shot 2018-03-02 at 1 45 52 pm](https://user-images.githubusercontent.com/17437436/36923982-d4560e20-1e21-11e8-87da-8730f4e859a1.png)
* pdol/cmore would like us to survey users on `introduction-confirmation-leave-study`, so can you make sure that survey is modified appropriately for that exit condition?

**Comment by rayborn** [comment]
- Fixed the 'user-disable' explicit question about disabling
- [DIFFERENT THAN THE ABOVE AFTER SLACK CONVERSATION] Created a very simple survey for 'introduction-confirmation-leave-study' users that asks them why they aren't participating and gets a general star rating for comparison against other branches
- Fixed, thanks SG changed the Star CSS which caused an issue with singular star grids
- I think this is covered by the new very simple path we created

I'm retesting all flows once more, but I think we're almost ready to launch (will ping)

**Comment by rayborn** [comment]
W also added:

- "user-enabled-auto-private-browsing" - Basically, if at any point they change a pref that turns all windows into private windows, we end the study.
- "user-installed-ad-blocker" - user installed an ad blocker which would confound our results.
