### ISSUE TITLE
Get a QA review

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#28]
As part of the standard Shield study development process, this study should receive a QA review.

This is a meta-issue for any QA-related concerns.

QA reviewer: pdehaan

**Comment by pdehaan** [comment]
Everything looks good to me! 👍 

![](https://media.giphy.com/media/MHBxC3uR71Yyc/giphy.gif)

**Comment by biancadanforth** [comment]
Great thank you Peter!
