### ISSUE TITLE
Set telemetry flags in Config.jsm correctly for deployment

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#30]
Currently during testing, it is possible to specify:
1. Whether telemetry pings are actually sent
2. Whether or not to mark sent telemetry pings with a "testing" flag

Make sure in the final version of the addon, `telemetry.send = true` and `telemetry.removeTestingFlag = true` in `Config.jsm`.

**Comment by gregglind** [comment]
Let's see if we can flip them now, and tell pipepline to ignore pre-normandy launch pings?
