### ISSUE TITLE
Implement any eligibility requirements for the study

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#35]
These are handled in `Config.jsm` in the `isEligible()` method.

Outside of the "Audience Definition" from the [original PHD](https://docs.google.com/document/d/1OJq1EDMNqydNoR8Ui_916Uzq7SHq9rl0bfZTmO5dC3g/edit#heading=h.1vb6dqrhf3eo), which I gather will be specified in Normandy, are there any eligibility requirements that should be enforced via the addon?

### Eligibility
* The user has not modified built-in Tracking Protection from its default setting (enabled in Private Browsing mode only).

---------------
@MattGrimes, @gregglind, can you think of anything else?

**Comment by MattGrimes** [comment]
The user can't having tracking protection enabled by default. We can try to
control that from the Normandy end, but it might also be worth doing so in
the add-on. Maybe some basic version and channel enforcement as well to
ensure we're getting Release users on 57+. @gregglind ?

**Comment by biancadanforth** [comment]
Confirmed with Gregg that just just checking Tracking Protection setting has not been modified is enough for the addon. Normandy can check for version/channel.
