### ISSUE TITLE
In the "fast" variation, consider replacing shield with clock on about:newtab

### ISSUE THREAD

**Issue by groovecoder** [biancadanforth/tracking-protection-shield-study#45]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/71928/35064853-f6167ddc-fb90-11e7-814e-ac33b13503b8.png">

I love the way this section feels in the about:newtab page - it really helps to reinforce how Firefox is helping the user.

In the "fast" variation, it might emphasize the time benefit even more if the icon is changed to a clock instead of a shield?

**Comment by biancadanforth** [comment]
@jsavory, what do you think about this? If you approve, let me know what clock icon to use.

**Comment by pdehaan** [comment]
Unrelated, but in the screenshot above, I'm not exactly sure what "0.22 minutes" is without a pen, paper and a lot of maths. Not sure if it'd make more sense to convert to seconds if the value is <1. (Spoiler alert, it'd be ~13.2 seconds)
Similarly, telling me "219.54 minutes" would be equally awkward (versus saying "3.65 hours" or "3 hours and 39 minutes"...) Dates are hard.

**Comment by biancadanforth** [comment]
Great observation @pdehaan ; I will make those changes as part of resolving this issue as well.

**Comment by biancadanforth** [comment]
Quoting @jsavory,
>Also I tried out the clock icon for the speed version, and I feel like it doesn't have the effect we were hoping for. Something about lacking the shield icon made the doorhanger and time icon look off. So let's stick with the shield for all versions for now.

Will leave this issue open for pdehaan's comment. Until that's fixed.

**Comment by pdehaan** [comment]
> Will leave this issue open for pdehaan's comment. Until that's fixed.

I moved my unrelated comments to #65, so feel free to close this issue.

**Comment by biancadanforth** [comment]
Okay probably a better idea anyway; closing.
