### ISSUE TITLE
Inconsistent results between awesomebar, dropdown, and new tab

### ISSUE THREAD

**Issue by pdehaan** [biancadanforth/tracking-protection-shield-study#58]
### Steps to reproduce:

1. Run `npm run firefox`.
1. Set `extensions.tracking_protection_messaging_study.variation_override` flag to "fast".
1. Reload temporary extension.
1. Visit https://www.msn.com/en-ca/

### Actual results:

<img width="562" alt="msn_ca" src="https://user-images.githubusercontent.com/557895/35297956-717e4d6c-0035-11e8-805d-811c46f5bef4.png">

<img width="400" alt="newrtab" src="https://user-images.githubusercontent.com/557895/35298327-a7eda432-0036-11e8-99c0-7f3a6920c73e.png">

Awesome bar says I've saved 7 seconds of my life.
The dropdown menu says 0 trackers blocked and 0 seconds saved.
The new tab page says 0 trackers blocked today and 0.26 minutes saved. (which is roughly 15.6 seconds).

**Comment by biancadanforth** [comment]
Hmmm still seeing this occur, so reopening >.>

**Comment by pdehaan** [comment]
![buzzfeed](https://user-images.githubusercontent.com/557895/36496504-53a33838-16ed-11e8-81d3-de31c1f08e9b.png)

I'd need to try digging through code to see if one is doing a `Math.round()` and another is not, or if something is doing `.floor()` vs `.ceil()`.

Oddly, I'm not seeing any messaging on my about:home page in today's FF Nightly to confirm what that page says.

**Comment by pdehaan** [comment]
Note that this doesn't always happen. I see different results on the same site, so I think it's purely a rounding issue/edge case:

![mirror-co-uk-dinosaurs](https://user-images.githubusercontent.com/557895/36497088-2336fffc-16ef-11e8-8ed6-cea7e289fe35.png)
