### ISSUE TITLE
Clear up all TODO/FIXME comments in code and lint

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#74]
There are a number of TODOs in the code; before shipping, they should be addressed, the corresponding [eslint rule](https://github.com/biancadanforth/tracking-protection-shield-study/blob/1d7de44f860a5af454f0701e59434bd2654503a9/.eslintrc.js#L44) should be updated and the code should be linted.

**Comment by pdehaan** [comment]
In #95 PR, I added a bunch more "TODO" comments for the docs, which may obscure P1 code TODO comments. Let me know if you want me to change the JSDoc TODOs to something else which we can toggle separately.
