### ISSUE TITLE
Ensure code dependencies are correctly declared in package.json

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#78]
From the Security Review:

ShieldUtils.jsm is incorrectly listed as a devDependency rather than a Dependency in `package.json`. If the code ships with the addon, it should be included in the repo.

Bring in changes from Disconnect lists right before.

**Comment by pdehaan** [comment]
Related: #56; __"Audit potentially unused dependencies"__
