### ISSUE TITLE
Sending message that cannot be cloned... error in browser console

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#79]
I get this error message in the browser console seemingly every time a message is passed from Feature.jsm to the frame script `new-tab-variation.js`.

```
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  Feature.jsm:720:8
```

The line of code in question is:

```javascript
Services.mm.broadcastAsyncMessage("TrackingStudy:UpdateContent", {
  state: this.state,
});
```

**Comment by gregglind** [comment]
it means that 'this.state' is not jsonable for some reason.  

Bianca claimed it's bcause there are Maps().  

Gregg has solved this in past by having a helper function to copy out specific subset of fields.   I do not like this solution.

**Comment by biancadanforth** [comment]
If it's used more than once: Use a helper funciton to turn the state object into one of these object type in a little factory at the top of Feature.jsm.
